# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui',
# licensing of 'main.ui' applies.
#
# Created: Sun Jul  7 16:13:44 2019
#      by: pyside2-uic  running on PySide2 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 768)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setHandleWidth(10)
        self.splitter.setObjectName("splitter")
        self.left_sidebar = QtWidgets.QWidget(self.splitter)
        self.left_sidebar.setObjectName("left_sidebar")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.left_sidebar)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.left_sidebar)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.area_index = QtWidgets.QComboBox(self.left_sidebar)
        self.area_index.setObjectName("area_index")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.area_index)
        self.label_2 = QtWidgets.QLabel(self.left_sidebar)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.room_index = QtWidgets.QComboBox(self.left_sidebar)
        self.room_index.setObjectName("room_index")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.room_index)
        self.verticalLayout_2.addLayout(self.formLayout)
        self.map_graphics_view = QtWidgets.QGraphicsView(self.left_sidebar)
        self.map_graphics_view.setObjectName("map_graphics_view")
        self.verticalLayout_2.addWidget(self.map_graphics_view)
        self.entity_lists_list = QtWidgets.QListWidget(self.left_sidebar)
        self.entity_lists_list.setObjectName("entity_lists_list")
        self.verticalLayout_2.addWidget(self.entity_lists_list)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.scrollArea = QtWidgets.QScrollArea(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 684, 707))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.room_graphics_view = RoomView(self.scrollAreaWidgetContents)
        self.room_graphics_view.setObjectName("room_graphics_view")
        self.verticalLayout.addWidget(self.room_graphics_view)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.right_sidebar = QtWidgets.QTabWidget(self.splitter)
        self.right_sidebar.setMinimumSize(QtCore.QSize(300, 0))
        self.right_sidebar.setObjectName("right_sidebar")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.entity_properies = EntityProperties(self.tab)
        self.entity_properies.setObjectName("entity_properies")
        self.verticalLayout_6.addWidget(self.entity_properies)
        self.right_sidebar.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.bg2_tileset_graphics_view = QtWidgets.QGraphicsView(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bg2_tileset_graphics_view.sizePolicy().hasHeightForWidth())
        self.bg2_tileset_graphics_view.setSizePolicy(sizePolicy)
        self.bg2_tileset_graphics_view.setObjectName("bg2_tileset_graphics_view")
        self.verticalLayout_7.addWidget(self.bg2_tileset_graphics_view)
        self.right_sidebar.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.tab_3)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.bg1_tileset_graphics_view = QtWidgets.QGraphicsView(self.tab_3)
        self.bg1_tileset_graphics_view.setObjectName("bg1_tileset_graphics_view")
        self.verticalLayout_8.addWidget(self.bg1_tileset_graphics_view)
        self.right_sidebar.addTab(self.tab_3, "")
        self.horizontalLayout.addWidget(self.splitter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1280, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        self.menuTools = QtWidgets.QMenu(self.menubar)
        self.menuTools.setObjectName("menuTools")
        self.menuBuild = QtWidgets.QMenu(self.menubar)
        self.menuBuild.setObjectName("menuBuild")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionLayer_BG1 = QtWidgets.QAction(MainWindow)
        self.actionLayer_BG1.setCheckable(True)
        self.actionLayer_BG1.setChecked(True)
        self.actionLayer_BG1.setObjectName("actionLayer_BG1")
        self.actionLayer_BG2 = QtWidgets.QAction(MainWindow)
        self.actionLayer_BG2.setCheckable(True)
        self.actionLayer_BG2.setChecked(True)
        self.actionLayer_BG2.setObjectName("actionLayer_BG2")
        self.actionEntities = QtWidgets.QAction(MainWindow)
        self.actionEntities.setCheckable(True)
        self.actionEntities.setChecked(True)
        self.actionEntities.setObjectName("actionEntities")
        self.actionTile_Entities = QtWidgets.QAction(MainWindow)
        self.actionTile_Entities.setCheckable(True)
        self.actionTile_Entities.setChecked(True)
        self.actionTile_Entities.setObjectName("actionTile_Entities")
        self.actionExits = QtWidgets.QAction(MainWindow)
        self.actionExits.setCheckable(True)
        self.actionExits.setChecked(True)
        self.actionExits.setObjectName("actionExits")
        self.actionEntity_Search = QtWidgets.QAction(MainWindow)
        self.actionEntity_Search.setObjectName("actionEntity_Search")
        self.actionTest_Room = QtWidgets.QAction(MainWindow)
        self.actionTest_Room.setObjectName("actionTest_Room")
        self.actionLayer_BG3 = QtWidgets.QAction(MainWindow)
        self.actionLayer_BG3.setCheckable(True)
        self.actionLayer_BG3.setChecked(True)
        self.actionLayer_BG3.setObjectName("actionLayer_BG3")
        self.actionSave_Editor = QtWidgets.QAction(MainWindow)
        self.actionSave_Editor.setObjectName("actionSave_Editor")
        self.actionText_Editor = QtWidgets.QAction(MainWindow)
        self.actionText_Editor.setObjectName("actionText_Editor")
        self.actionNew_Project = QtWidgets.QAction(MainWindow)
        self.actionNew_Project.setObjectName("actionNew_Project")
        self.actionOpen_Project = QtWidgets.QAction(MainWindow)
        self.actionOpen_Project.setObjectName("actionOpen_Project")
        self.actionSave_Project = QtWidgets.QAction(MainWindow)
        self.actionSave_Project.setObjectName("actionSave_Project")
        self.actionSave_Project_As = QtWidgets.QAction(MainWindow)
        self.actionSave_Project_As.setObjectName("actionSave_Project_As")
        self.menuFile.addAction(self.actionNew_Project)
        self.menuFile.addAction(self.actionOpen_Project)
        self.menuFile.addAction(self.actionSave_Project)
        self.menuFile.addAction(self.actionSave_Project_As)
        self.menuView.addAction(self.actionLayer_BG1)
        self.menuView.addAction(self.actionLayer_BG2)
        self.menuView.addAction(self.actionLayer_BG3)
        self.menuView.addAction(self.actionEntities)
        self.menuView.addAction(self.actionTile_Entities)
        self.menuView.addAction(self.actionExits)
        self.menuTools.addAction(self.actionEntity_Search)
        self.menuTools.addAction(self.actionSave_Editor)
        self.menuTools.addAction(self.actionText_Editor)
        self.menuBuild.addAction(self.actionTest_Room)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())
        self.menubar.addAction(self.menuBuild.menuAction())

        self.retranslateUi(MainWindow)
        self.right_sidebar.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "Minish Cap Editor", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("MainWindow", "Area", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("MainWindow", "Room", None, -1))
        self.right_sidebar.setTabText(self.right_sidebar.indexOf(self.tab), QtWidgets.QApplication.translate("MainWindow", "Entities", None, -1))
        self.right_sidebar.setTabText(self.right_sidebar.indexOf(self.tab_2), QtWidgets.QApplication.translate("MainWindow", "BG2", None, -1))
        self.right_sidebar.setTabText(self.right_sidebar.indexOf(self.tab_3), QtWidgets.QApplication.translate("MainWindow", "BG1", None, -1))
        self.menuFile.setTitle(QtWidgets.QApplication.translate("MainWindow", "File", None, -1))
        self.menuView.setTitle(QtWidgets.QApplication.translate("MainWindow", "View", None, -1))
        self.menuTools.setTitle(QtWidgets.QApplication.translate("MainWindow", "Tools", None, -1))
        self.menuBuild.setTitle(QtWidgets.QApplication.translate("MainWindow", "Build", None, -1))
        self.actionLayer_BG1.setText(QtWidgets.QApplication.translate("MainWindow", "Layer BG1", None, -1))
        self.actionLayer_BG2.setText(QtWidgets.QApplication.translate("MainWindow", "Layer BG2", None, -1))
        self.actionEntities.setText(QtWidgets.QApplication.translate("MainWindow", "Entities", None, -1))
        self.actionTile_Entities.setText(QtWidgets.QApplication.translate("MainWindow", "Tile Entities", None, -1))
        self.actionExits.setText(QtWidgets.QApplication.translate("MainWindow", "Exits", None, -1))
        self.actionEntity_Search.setText(QtWidgets.QApplication.translate("MainWindow", "Entity Search", None, -1))
        self.actionEntity_Search.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+F", None, -1))
        self.actionTest_Room.setText(QtWidgets.QApplication.translate("MainWindow", "Test Room", None, -1))
        self.actionTest_Room.setShortcut(QtWidgets.QApplication.translate("MainWindow", "F7", None, -1))
        self.actionLayer_BG3.setText(QtWidgets.QApplication.translate("MainWindow", "Layer BG3", None, -1))
        self.actionSave_Editor.setText(QtWidgets.QApplication.translate("MainWindow", "Save Editor", None, -1))
        self.actionSave_Editor.setShortcut(QtWidgets.QApplication.translate("MainWindow", "V", None, -1))
        self.actionText_Editor.setText(QtWidgets.QApplication.translate("MainWindow", "Text Editor", None, -1))
        self.actionText_Editor.setShortcut(QtWidgets.QApplication.translate("MainWindow", "T", None, -1))
        self.actionNew_Project.setText(QtWidgets.QApplication.translate("MainWindow", "New Project", None, -1))
        self.actionOpen_Project.setText(QtWidgets.QApplication.translate("MainWindow", "Open Project", None, -1))
        self.actionSave_Project.setText(QtWidgets.QApplication.translate("MainWindow", "Save Project", None, -1))
        self.actionSave_Project_As.setText(QtWidgets.QApplication.translate("MainWindow", "Save Project As", None, -1))

from mcedit_ui.room_view import RoomView
from mcedit_ui.entity_properties import EntityProperties
