# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sprite_editor.ui',
# licensing of 'sprite_editor.ui' applies.
#
# Created: Fri Jul 12 21:42:51 2019
#      by: pyside2-uic  running on PySide2 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_SpriteEditor(object):
    def setupUi(self, SpriteEditor):
        SpriteEditor.setObjectName("SpriteEditor")
        SpriteEditor.resize(832, 478)
        self.verticalLayout = QtWidgets.QVBoxLayout(SpriteEditor)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tabWidget = QtWidgets.QTabWidget(SpriteEditor)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.enemy_list = QtWidgets.QListWidget(self.tab)
        self.enemy_list.setObjectName("enemy_list")
        self.verticalLayout_3.addWidget(self.enemy_list)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.object_list = QtWidgets.QListWidget(self.tab_2)
        self.object_list.setObjectName("object_list")
        self.verticalLayout_4.addWidget(self.object_list)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tab_3)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.npc_list = QtWidgets.QListWidget(self.tab_3)
        self.npc_list.setObjectName("npc_list")
        self.verticalLayout_5.addWidget(self.npc_list)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.tab_4)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.player_list = QtWidgets.QListWidget(self.tab_4)
        self.player_list.setObjectName("player_list")
        self.verticalLayout_6.addWidget(self.player_list)
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.tab_5)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.type_4s_list = QtWidgets.QListWidget(self.tab_5)
        self.type_4s_list.setObjectName("type_4s_list")
        self.verticalLayout_7.addWidget(self.type_4s_list)
        self.tabWidget.addTab(self.tab_5, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.tab_6)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.player_items_list = QtWidgets.QListWidget(self.tab_6)
        self.player_items_list.setObjectName("player_items_list")
        self.verticalLayout_8.addWidget(self.player_items_list)
        self.tabWidget.addTab(self.tab_6, "")
        self.horizontalLayout.addWidget(self.tabWidget)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(SpriteEditor)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.form_index = QtWidgets.QComboBox(SpriteEditor)
        self.form_index.setObjectName("form_index")
        self.horizontalLayout_2.addWidget(self.form_index)
        self.verticalLayout_9.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(SpriteEditor)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.anim_index = QtWidgets.QComboBox(SpriteEditor)
        self.anim_index.setObjectName("anim_index")
        self.horizontalLayout_3.addWidget(self.anim_index)
        self.label_2 = QtWidgets.QLabel(SpriteEditor)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.frame_index = QtWidgets.QComboBox(SpriteEditor)
        self.frame_index.setObjectName("frame_index")
        self.horizontalLayout_3.addWidget(self.frame_index)
        self.verticalLayout_9.addLayout(self.horizontalLayout_3)
        self.verticalLayout_2.addLayout(self.verticalLayout_9)
        self.sprite_graphics_view = QtWidgets.QGraphicsView(SpriteEditor)
        self.sprite_graphics_view.setObjectName("sprite_graphics_view")
        self.verticalLayout_2.addWidget(self.sprite_graphics_view)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(SpriteEditor)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(SpriteEditor)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), SpriteEditor.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), SpriteEditor.reject)
        QtCore.QMetaObject.connectSlotsByName(SpriteEditor)

    def retranslateUi(self, SpriteEditor):
        SpriteEditor.setWindowTitle(QtWidgets.QApplication.translate("SpriteEditor", "Text Editor", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtWidgets.QApplication.translate("SpriteEditor", "Enemies", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtWidgets.QApplication.translate("SpriteEditor", "Objects", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QtWidgets.QApplication.translate("SpriteEditor", "NPCs", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), QtWidgets.QApplication.translate("SpriteEditor", "Player", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), QtWidgets.QApplication.translate("SpriteEditor", "Type 4s", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), QtWidgets.QApplication.translate("SpriteEditor", "Player Items", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("SpriteEditor", "Form", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("SpriteEditor", "Animation", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("SpriteEditor", "Frame", None, -1))

